apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongo-data
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
