apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: flask-mongo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongo-root
  MONGO_INITDB_ROOT_PASSWORD: StrongPassword123
